# Generated by Django 3.2.9 on 2021-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('totalpoints', models.TextField(max_length=10)),
                ('pointsearned', models.TextField(max_length=10)),
            ],
        ),
    ]
