# Generated by Django 3.2.9 on 2021-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=24)),
                ('customer_name', models.TextField(max_length=64)),
                ('birthday', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=124)),
                ('total_points', models.TextField(max_length=10)),
                ('points_earned', models.TextField(max_length=10)),
                ('points_spent', models.TextField(max_length=10)),
            ],
        ),
    ]
