# Generated by Django 3.2.9 on 2021-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial_defaults = [
        {
            "id": 1,
            "username": "jmoulton",
            "customer_name": "Jodi Moulton",
            "birthday": "June 30, 1997",
            "address": "3924 Cinnamon Lane San Antonio, TX 78258",
            "total_points": "1305",
            "points_earned": "65164",
            "points_spent": "63859"
        },
        {
            "id": 2,
            "username": "rsmith",
            "customer_name": "Richard Smith",
            "birthday": "December 20, 1943",
            "address": "2349 American Drive Panama City, FL 32401",
            "total_points": "645",
            "points_earned": "1254",
            "points_spent": "609"
        },
        {
            "id": 3,
            "username": "dmaule",
            "customer_name": "Dorothy Maule",
            "birthday": "August 15, 1958",
            "address": "3613 Hedge Street Bedminster, NJ 07921",
            "total_points": "1654",
            "points_earned": "1654",
            "points_spent": "0"
        },
        {
            "id": 4,
            "username": "jnolan",
            "customer_name": "Joan Nolan",
            "birthday": "August 31, 1984",
            "address": "12 Ashmor Drive Wadena, MN 56482",
            "total_points": "16548",
            "points_earned": "19456",
            "points_spent": "2908"
        }
    ]

    def insert_defaults(apps, schema_editor):
        User = apps.get_model("user_profile", "User")
        for row in Migration.initial_defaults:
            user = User(**row)
            user.save()

    def remove_defaults(apps, schema_editor):
        User = apps.get_model("user_profile", "User")
        for row in Migration.initial_defaults:
            user = User(**row)
            user.delete()
    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_defaults, remove_defaults)
    ]
