# Generated by Django 3.2.9 on 2021-12-03 02:01

from django.db import migrations


class Migration(migrations.Migration):
    initial_defaults = [
        {
            "id": 1,
            "username": "jmoulton",
            "password": "password1",
            "name": "Jodi Moulton",
            "birthday": "June 30, 1997",
            "address": "3924 Cinnamon Lane San Antonio, TX 78258",
            "totalpoints": "1305",
            "pointsearned": "65164"
        },
        {
            "id": 2,
            "username": "rsmith",
            "password": "password2",
            "name": "Richard Smith",
            "birthday": "December 20, 1943",
            "address": "2349 American Drive Panama City, FL 32401",
            "totalpoints": "645",
            "pointsearned": "1254"
        },
        {
            "id": 3,
            "username": "dmaule",
            "password": "password3",
            "name": "Dorothy Maule",
            "birthday": "August 15, 1958",
            "address": "3613 Hedge Street Bedminster, NJ 07921",
            "totalpoints": "1654",
            "pointsearned": "1654"
        },
        {
            "id": 4,
            "username": "jnolan",
            "password": "password4",
            "name": "Joan Nolan",
            "birthday": "August 31, 1984",
            "address": "12 Ashmor Drive Wadena, MN 56482",
            "totalpoints": "16548",
            "pointsearned": "19456"
        }
    ]

    def insert_defaults(apps, schema_editor):
        User = apps.get_model("user_profile", "User")
        for row in Migration.initial_defaults:
            user = User(**row)
            user.save()

    def remove_defaults(apps, schema_editor):
        User = apps.get_model("user_profile", "User")
        for row in Migration.initial_defaults:
            user = User(**row)
            user.delete()

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_defaults, remove_defaults)
    ]
